title: Feedback
handlers:
  email_confirmation:
    label: 'Courriel de confirmation'
    settings:
      from_name: _default
      subject: _default
  email_notification:
    label: 'Notification par courriel'
    settings:
      from_name: '[webform_submission:values:name:raw]'
      subject: _default
